VFS-3989 Updated charts

diff --git a/charts/oneclient/templates/deployment.yaml b/charts/oneclient/templates/deployment.yaml
--- a/charts/oneclient/templates/deployment.yaml
+++ b/charts/oneclient/templates/deployment.yaml
@@ -5,7 +5,7 @@ metadata:
   labels:
     app: {{ template "fullname" . }}
     chart: "{{ .Chart.Name }}"
-    release: "{{ .Release.Name }}"
+    release: "{{ template "releaseName" . }}"
     heritage: "{{ .Release.Service }}"
   annotations:
     version: "{{ .Chart.Version }}"
@@ -15,67 +15,54 @@ spec:
       labels:
         app: {{ template "fullname" . }}
         chart: "{{ .Chart.Name }}"
-        release: "{{ .Release.Name }}"
+        release: "{{ template "releaseName" . }}"
         heritage: "{{ .Release.Service }}"
       annotations:
         version: "{{ .Chart.Version }}"
-        pod.beta.kubernetes.io/init-containers: '[
-            {
-                "name": "wait-for-onezone",
-                "image": "{{ .Values.wait_for.image }}",
-                "imagePullPolicy": "{{ default .Values.wait_for.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}",
-{{ include "imagePullSecrets_json" . | indent 16 }}
-                "args": [
-                    "pod", "-lapp={{ template "onezone_name" . }}"
-                ]
-            },
-            {
-                "name": "get-client-token",
-                "image": "{{ .Values.onedata_cli.image }}",
-                "imagePullPolicy": "{{ default .Values.onedata_cli.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}",
-{{ include "imagePullSecrets_json" . | indent 16 }}
-                "env": [
-                    {
-                        "name": "ONEZONE_HOST",
-                        "value": "https://{{ template "onezone_name" . }}"
-                    },
-                    {
-                        "name": "ONEZONE_BASIC_AUTH",
-                        "value": "admin:password"
-                    }
-                ],
-                "command": [
-                    "sh", "-c",
-                    "curl -k -u $ONEZONE_BASIC_AUTH -X POST -d \"\" -H \"content-type: application/json\" $ONEZONE_HOST/api/v3/onezone/user/client_tokens | jq -r \".token\" > /shared/token  ;"
-                ],
-                "volumeMounts": [
-                    {
-                        "mountPath": "/shared/",
-                        "name": "shared"
-                    }
-                ]
-            },
-            {
-                "name": "wait-for-oneprovider",
-                "image": "{{ .Values.wait_for.image }}",
-                "imagePullPolicy": "{{ default .Values.wait_for.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}",
-{{ include "imagePullSecrets_json" . | indent 16 }}
-                "args": [
-                    "pod", "-lapp={{ template "oneprovider_name" . }}"
-                ]
-            }
-        ]'
     spec:
       hostname: {{ .Chart.Name }}
       subdomain: {{ template "fullname" . }}
+      replicas: {{ .Values.replicas }}
+    {{- if .Values.affinity }}
+      affinity:
+{{ toYaml .Values.affinity | indent 8 }}
+      {{- end }}
+    {{- if .Values.tolerations }}
+      tolerations:
+{{ toYaml .Values.tolerations | indent 8 }}
+      {{- end }}
+    {{- if .Values.nodeSelector }}
+      nodeSelector:
+{{ toYaml .Values.nodeSelector | indent 8 }}
+      {{- end }}
 {{ include "imagePullSecrets" . | indent 6 }}
       volumes:
       - name: shared
         emptyDir: {}
+      initContainers:
+        - name: wait-for-onezone
+          image: {{ .Values.wait_for.image }}
+          imagePullPolicy: {{ template "imagePullPolicy" .Values.wait_for }}
+          args:
+            - "job"
+            - "{{ template "onezone_name" . }}-ready-check"
+        - name: wait-for-token-dispenser
+          image: {{ .Values.wait_for.image }}
+          imagePullPolicy: {{ template "imagePullPolicy" .Values.wait_for }}
+          args:
+            - "pod"
+            - >
+              -lapp={{ template "token-dispenser_name" . }}
+        - name: wait-for-oneprovider
+          image: {{ .Values.wait_for.image }}
+          imagePullPolicy: {{ template "imagePullPolicy" .Values.wait_for }}
+          args:
+            - "job"
+            - "{{ template "oneprovider_name" . }}-ready-check" 
       containers:
       - name: {{ .Chart.Name }}
         image: {{ .Values.image }}
-        imagePullPolicy: {{ default .Values.imagePullPolicy .Values.global.imagePullPolicy | default "IfNotPresent" }}
+        imagePullPolicy: {{ template "imagePullPolicy" . }}
         env:
           - name: ONECLIENT_INSECURE
             value: "true"
@@ -87,23 +74,49 @@ spec:
          - "sh"
          - "-c"
          - >
-           export ONECLIENT_ACCESS_TOKEN=$(cat /shared/token) ;
-           cat /shared/token ;
-           {{ if .Values.debug_mode }}
-           oneclient "/mnt/oneclient" ;
+           echo "source /oneclient-mount.sh" >> ~/.bashrc ;
+           {{- range $user := .Values.users }}{{ if hasKey . "oneclient"  }}{{ if has $.Values.suffix $user.oneclient }}{{ if .idps }}
+           {{- if .idps.onepanel }}{{if .idps.onepanel.enabled }}
+           idp=onepanel;
+           {{- end }}{{ end }}
+           {{- if .idps.keycloak }}{{if .idps.keycloak.enabled }}
+           idp=keycloak-rhea;
+           {{- end }}{{ end }}
+           ONECLIENT_ACCESS_TOKEN=$(curl --silent -k -u {{ $user.name }}:{{ $user.password }} http://{{ template "token-dispenser_name" $ }}/api/v1.0/token/$idp);
+           mount_dir="/mnt/oneclient/{{ $user.name }}";
+           mkdir -p "$mount_dir";
+           echo "Mounting oneclient in $mount_dir for user={{ $user.name }}, from idp=$idp, using TOKEN=$ONECLIENT_ACCESS_TOKEN.";
+           oneclient -t $ONECLIENT_ACCESS_TOKEN "$mount_dir";
+           while ! mount | grep -q "$mount_dir" ; do
+           i=1;
+           max_i=30;
+           while ! mount| grep -q "$mount_dir" && [ $i -le $max_i ] ; do echo "Wainting ${i}/${max_i} time for mount $mount_dir. Sleeping for 2 seconds." ; i=$((i+1)) ; sleep 2 ; done ;
+           if mount | grep -q /mnt/oneclient/meg ; then break ; else echo "Failed to mount $mount_dir retrying to run oneclient for dir=$mount_dir" ; fi  ;
+           done ;
+           echo "Success, mounted $mount_dir." ;
+           {{- end }}{{ end }}{{ end }}{{ end }}
+           echo "All clients have been mounted." ;
+           touch /all_oneclients_mounted ;
            sleep infinity ;
-           {{ else }}
-           oneclient -f "/mnt/oneclient" ;
-           {{ end }}
         readinessProbe:
           exec:
             command:
-             - "sh"
-             - "-c"
-             - >
-                mount | grep /mnt/oneclient ;
+             - cat 
+             - /all_oneclients_mounted
         securityContext:
           privileged: true
         volumeMounts:
         - mountPath: /shared
           name: shared
+        volumeMounts:
+          - mountPath: /oneclient-mount.sh
+            subPath: oneclient-mount.sh
+            name: oneclient-mount
+            readOnly: true
+      volumes:
+      - name: oneclient-mount
+        configMap:
+          name: {{ template "fullname" . }}-config
+          items:
+          - key: oneclient-mount.sh
+            path: oneclient-mount.sh
